// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi4C6rZ-zfdL7q7pU15JVNOXIZpRateac',
    appId: '1:421579137537:web:77586bac7d5ebd01329600',
    messagingSenderId: '421579137537',
    projectId: 'vivar-63f29',
    authDomain: 'vivar-63f29.firebaseapp.com',
    storageBucket: 'vivar-63f29.firebasestorage.app',
    measurementId: 'G-08YTF2XPY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF57YaTECy4L4wsKqncWFbtmf95r-jO-Y',
    appId: '1:421579137537:android:ec10a3b8c2243c9d329600',
    messagingSenderId: '421579137537',
    projectId: 'vivar-63f29',
    storageBucket: 'vivar-63f29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB57pGzMYSSlFe8tLkeRj12mimBRvx04o4',
    appId: '1:421579137537:ios:a0f063b1e83c1dae329600',
    messagingSenderId: '421579137537',
    projectId: 'vivar-63f29',
    storageBucket: 'vivar-63f29.firebasestorage.app',
    iosBundleId: 'com.example.vivar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB57pGzMYSSlFe8tLkeRj12mimBRvx04o4',
    appId: '1:421579137537:ios:a0f063b1e83c1dae329600',
    messagingSenderId: '421579137537',
    projectId: 'vivar-63f29',
    storageBucket: 'vivar-63f29.firebasestorage.app',
    iosBundleId: 'com.example.vivar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi4C6rZ-zfdL7q7pU15JVNOXIZpRateac',
    appId: '1:421579137537:web:8992b44f3e145f7d329600',
    messagingSenderId: '421579137537',
    projectId: 'vivar-63f29',
    authDomain: 'vivar-63f29.firebaseapp.com',
    storageBucket: 'vivar-63f29.firebasestorage.app',
    measurementId: 'G-VK44BE7X43',
  );

}