name: authentication_module
description: Descrição do módulo
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  provider: ^6.1.1
  flutter:
    sdk: flutter
  core_module:
    path: ../core_module