name: splash_module
description: Descrição do módulo splash
version: 0.0.1

environment:
  sdk: ^3.8.1

dependencies:
  provider: ^6.1.1
  flutter:
    sdk: flutter
  core_module:
    path: ../core_module